### ISSUE TITLE
website overhaul

### ISSUE THREAD

**Issue by aschuerch** [MMB-UMCU/mmb-bioit#35]
What areas need to be improved? Leave your observations as a comment

**Comment by gidjes** [comment]
See out tools link on main page does not work

**Comment by aschuerch** [comment]
less sad banner picture for the landing page

**Comment by JesseKerkvliet** [comment]
- Update links (the tools link in the main page is dead, links to resources in stead of tools)
- Update graphics (new group photo, nicer picture of the UMC?)
- Update the tools page with clonal tracker
- Add twitter feed to main page?

**Comment by MalbertRogers** [comment]
Home/Landing page is a bit bland. We should think about how to make it more interesting and attractive to the eyes.

**Comment by weizhenxuuu** [comment]
- new zoom photo with everyone
- alumni page/info
- link to clonaltracker

**Comment by MatteoBuffoni** [comment]
- [ ] Adjust tool tags "Plasmid/s", Bactofidia doesn't have any.
- [ ] New picture of the team and maybe of the UMC (one with sun)?
- [ ]  Maybe in news a track record of the conferences, posters/presentations and prizes (Julian's) the the members

**Comment by jpaganini** [comment]
- [ ] Tools section: Update description of some tools (plasmidEC, bactofidia). Fix italic species. Add clonal tracker website.
- [ ] Main Section: Change main image maybe? It is a bit pixelated.
- [ ] Social networks: Create and add a mastodon account. Many scientist are moving to this platform after Elon acquired twitter

**Comment by janettatop** [comment]
- Research: is now only focussed on plasmid and genomics. Add taxonomic profiling and metagenomics
- Tools: add tourmaline?
- Team: of course an update of pictures and persons
- Blog: maybe discuss the purpose of this.
- Update the contacts site

**Comment by aschuerch** [comment]
Closing this issue as it was summarized in issues #36 #37 #38 #39 #40 #41
